apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://admin:WCbDeqdruVLm6p4k@cluster0.y0r9q.mongodb.net/taskpilot?retryWrites=true&w=majority&appName=Cluster0"
  SESSION_SECRET:  "3f9a1c7d8e4b6f5a2d0c9e7b1a3f8d4e6b7c0f2d5e9a8c1b3d4f6a7e9c0d2b5"
