apiVersion: apps/v1
kind: Deployment
metadata:
  name: yesonit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yesonit
  template:
    metadata:
      labels:
        app: yesonit
    spec:
      containers:
      - name: yesonit
        image: australia-southeast1-docker.pkg.dev/sit737-25t1-sabana-47965ad/yesonit-cdrm/yesonit-cdrm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3739
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URI
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: SESSION_SECRET
        - name: PORT
          value: "3739"