apiVersion: apps/v1
kind: Deployment
metadata:
  name: yesonit-cdrm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yesonit-cdrm
  template:
    metadata:
      labels:
        app: yesonit-cdrm
    spec:
      containers:
        - name: yesonit-cdrm
          image: australia-southeast1-docker.pkg.dev/sit737-25t1-sabana-47965ad/yesonit-cdrm/yesonit-cdrm:latest
          ports:
            - containerPort: 5737
          env:
            - name: PORT
              value: "5737"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: SESSION_SECRET