apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeson8-cdrm-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yeson8-cdrm
  template:
    metadata:
      labels:
        app: yeson8-cdrm
    spec:
      containers:
        - name: yeson8-cdrm
          image: australia-southeast1-docker.pkg.dev/radiant-destiny-435817-a8/yeson8-cdrm/yeson8-cdrm:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: SESSION_SECRET
      imagePullSecrets:
        - name: regcred