apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yeson8-cdrm-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yeson8-cdrm-app  # This is the name of your running deployment
  minReplicas: 1             # Minimum number of pods (always keep at least 1 running)
  maxReplicas: 5             # Maximum number of pods allowed under heavy load
  targetCPUUtilizationPercentage: 50  # Target CPU usage; scale up/down based on this